# Generated by Django 6.1 on 2026-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('keycloak_sub', models.CharField(help_text="Identifiant stable de l'utilisateur, issu du jeton (claim sub).", max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.TextField(help_text='Cle publique RSA, format SPKI base64.')),
                ('encrypted_private_key', models.TextField(help_text='Cle privee PKCS8 chiffree en AES-256-GCM, base64.')),
                ('private_key_iv', models.CharField(help_text="Vecteur d'initialisation AES-GCM, base64.", max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cles utilisateur',
                'verbose_name_plural': 'Cles utilisateur',
            },
        ),
    ]
