# Generated by Django 6.1 on 2026-08-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('keycloak_sub', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medecin',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('keycloak_sub', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', "En attente d'approbation"), ('approved', 'Approuve')], max_length=16)),
                ('initiated_by', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Medecin')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Lien medecin-patient',
                'verbose_name_plural': 'Liens medecin-patient',
                'constraints': [models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_doctor_patient_link')],
            },
        ),
    ]
