# Generated by Django 6.1 on 2026-08-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_patient_doctorpatientlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeys',
            name='encrypted_signing_private_key',
            field=models.TextField(blank=True, default='', help_text='Cle privee de signature PKCS8 chiffree en AES-256-GCM, base64.'),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='signing_private_key_iv',
            field=models.CharField(blank=True, default='', help_text="Vecteur d'initialisation AES-GCM de la cle de signature, base64.", max_length=32),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='signing_public_key',
            field=models.TextField(blank=True, default='', help_text='Cle publique RSA-PSS de signature, format SPKI base64.'),
        ),
    ]
