# Generated by Django 6.1 on 2026-08-23 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_doctor_patient_doctorpatientlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.TextField(help_text='Bloc chiffre AES-256-GCM, base64.')),
                ('iv', models.CharField(help_text="Vecteur d'initialisation, base64.", max_length=32)),
                ('status', models.CharField(choices=[('approved', 'Approuve'), ('pending_approval', "En attente d'approbation"), ('pending_deletion', 'Suppression en attente')], default='approved', max_length=20)),
                ('uploaded_by', models.CharField(help_text="keycloak_sub de l'auteur du depot.", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Fichier medical',
                'verbose_name_plural': 'Fichiers medicaux',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='JSON signe : {"version": n, "files": ["uuid", ...]}')),
                ('signature', models.TextField(help_text='Signature RSA-PSS du contenu, base64.')),
                ('version', models.PositiveIntegerField(default=0, help_text='Compteur monotone, refuse de reculer.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Manifeste de dossier',
                'verbose_name_plural': 'Manifestes de dossier',
            },
        ),
        migrations.CreateModel(
            name='WrappedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_sub', models.CharField(help_text="keycloak_sub de l'ayant droit.", max_length=64)),
                ('wrapped_dek', models.TextField(help_text='DEK chiffree en RSA-OAEP, base64.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_keys', to='records.medicalfile')),
            ],
            options={
                'verbose_name': 'Cle de fichier chiffree',
                'verbose_name_plural': 'Cles de fichier chiffrees',
                'constraints': [models.UniqueConstraint(fields=('file', 'recipient_sub'), name='unique_wrapped_key_per_recipient')],
            },
        ),
    ]
