services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: hospital
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.2
    command:
      - start-dev
      - --https-certificate-file=/opt/keycloak/certs/server.crt
      - --https-certificate-key-file=/opt/keycloak/certs/server.key
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HTTPS_PORT: 8443
    volumes:
      - ./certs:/opt/keycloak/certs:ro
    ports:
      - "8443:8443"

  django:
    build: ./backend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes:
      - ./certs:/certs:ro
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

volumes:
  db_data: