"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR.parent / ".env")

# Aucune valeur par defaut : Django refuse de demarrer si la variable est absente.
SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_extensions',
    'accounts',
    'records',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env.int("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# --- Email ------------------------------------------------------------
#
# AUCUN reglage MAILERS : cette application n'envoie pas d'email.
#
# Le bloc genere par `startproject` utilisait le backend `console`, qui
# AFFICHE les messages au lieu de les envoyer. Django refuse ce backend
# en production (mail.E001), et il a raison : un systeme qui croit
# envoyer des alertes alors qu'elles s'impriment dans un journal est
# pire que pas d'alerte du tout.
#
# Le seul composant qui aurait pu envoyer du courrier est l'admin
# Django (reinitialisation de mot de passe), desormais desactive hors
# developpement. On supprime donc le reglage plutot que de configurer un
# SMTP fictif : une configuration morte est une source d'erreur future.

# --- Validation des jetons Keycloak -----------------------------------
# Aucune valeur par defaut : l'application refuse de demarrer si une
# variable manque, plutot que de tourner avec une configuration partielle.
KEYCLOAK_ISSUER = env("KEYCLOAK_ISSUER")
KEYCLOAK_JWKS_URL = env("KEYCLOAK_JWKS_URL")
KEYCLOAK_AUDIENCE = env("KEYCLOAK_AUDIENCE")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.KeycloakAuthentication",
    ],
    # Tout endpoint exige un jeton valide, SAUF mention explicite du contraire.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "UNAUTHENTICATED_USER": None,
    # Limitation de debit. Les classes sont evaluees a chaque requete ;
    # AnonRateThrottle ne compte QUE les requetes non authentifiees.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "accounts.throttling.SubRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",  # visiteur anonyme : lecture de /api/health surtout
        "user": "120/min",  # usage normal : quelques appels par action
        "upload": "20/hour",  # depot de fichier : rare et couteux
    },
}

# Liste blanche stricte des origines autorisees a appeler l'API.
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS")
# Aucun cookie n'est utilise : l'authentification passe uniquement par
# l'en-tete Authorization. CSRF est donc sans objet sur cette API.
CORS_ALLOW_CREDENTIALS = False

# --- Durcissement (Phase 9) -------------------------------------------
#
# Ces reglages n'ont d'effet reel qu'avec DEBUG=False. Les laisser
# explicites plutot que de compter sur les valeurs par defaut de Django
# permet de les DEFENDRE un par un.

# HSTS : le navigateur memorise que ce domaine ne doit JAMAIS etre
# contacte en clair. Meme si l'utilisateur tape "http://", le navigateur
# corrige avant d'emettre la moindre requete.
#
# Valeur courte (1 heure) et NON preload, deliberement : une valeur d'un
# an gravee dans le navigateur du correcteur serait penible a annuler
# apres la demonstration. En production reelle : 31536000.
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=3600)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = False

# W021 (HSTS preload) est ECARTE VOLONTAIREMENT.
#
# La liste de prechargement HSTS est gravee en dur dans le code source
# des navigateurs. Un domaine qui y figure n'est plus JAMAIS contacte en
# clair, par aucun navigateur, meme a la premiere visite. En sortir prend
# des mois.
#
# Notre domaine est `localhost` : il designe la machine de celui qui tape
# l'adresse. Le prechargement n'a aucun sens ici, et personne ne peut
# d'ailleurs soumettre `localhost` a cette liste.
#
# On ecarte donc le controle en le JUSTIFIANT, plutot que de le
# satisfaire par une valeur qui serait fausse.
SILENCED_SYSTEM_CHECKS = ["security.W021"]

# Toute requete arrivant en clair est redirigee vers HTTPS.
SECURE_SSL_REDIRECT = not DEBUG

# Les cookies de session ne partent jamais en clair et sont invisibles
# au JavaScript. L'API n'utilise aucun cookie (authentification par
# en-tete Bearer), mais l'admin Django en pose : on les protege.
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True

# Actifs par defaut en Django 6 ; rendus explicites pour la relecture.
SECURE_CONTENT_TYPE_NOSNIFF = True   # pas de devinette de type MIME
X_FRAME_OPTIONS = "DENY"             # pas d'inclusion en iframe (clickjacking)
SECURE_REFERRER_POLICY = "same-origin"

# --- Journalisation ---------------------------------------------------
#
# Avec DEBUG=False, le client ne recoit qu'un message d'erreur generique :
# ni trace d'execution, ni requete SQL, ni variable d'environnement.
#
# Mais le detail ne doit pas disparaitre pour autant : il part dans le
# journal du conteneur, cote serveur, la ou seul l'exploitant le lit.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "{levelname} {asctime} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# --- Cache partage ----------------------------------------------------
#
# Indispensable a la limitation de debit : gunicorn tourne avec 3
# workers, donc 3 processus. Le cache par defaut (`LocMemCache`) est
# PROPRE A CHAQUE PROCESSUS : chacun tiendrait son propre compteur, et
# une limite de "30 par minute" en autoriserait 90.
#
# Une limite qu'on croit appliquer mais qui ne l'est pas est PIRE qu'une
# absence de limite : elle donne une fausse assurance.
#
# On utilise PostgreSQL, deja present, comme cache partage. Aucun service
# supplementaire a deployer, un seul compteur pour tous les workers.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}