# Generated by Django 6.1 on 2026-08-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='Fichier que celui-ci remplace (edition).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='records.medicalfile'),
        ),
    ]
